services:
  postgres:
    image: postgres:16
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: nestuser
      POSTGRES_PASSWORD: nestpassword
      POSTGRES_DB: nest-drizzle-prod
    volumes:
      # this creates a persistent volume to store database data
      # if docker is stopped/restarted, the data is not lost
      - db_data:/var/lib/postgresql/data 
      # Mount a local directory into the container's init folder.
      # Files in /docker-entrypoint-initdb.d run on first startup.
      - ./init-db-scripts:/docker-entrypoint-initdb.d

# Define the named volume for persistent data storage
volumes:
  db_data: